# Generated by Django 3.1 on 2020-09-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='uuid',
            field=models.CharField(default='aaaaa', max_length=5, verbose_name='Unique Code'),
            preserve_default=False,
        ),
    ]
