# Generated by Django 3.1 on 2020-09-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_auto_20200831_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='name',
            field=models.CharField(default='Company Name', max_length=100, verbose_name='Company Name'),
            preserve_default=False,
        ),
    ]
