# Generated by Django 3.1 on 2020-09-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_accountdetails_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatinghours',
            name='open',
        ),
    ]
