# Generated by Django 3.1 on 2020-08-31 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('queuer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
