# Generated by Django 3.1 on 2020-09-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuer', '0002_auto_20200831_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
