# Generated by Django 3.1 on 2020-09-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuer', '0003_queue_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='max_position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
