# Generated by Django 3.1 on 2020-09-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuer', '0006_auto_20200901_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='total_wait_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='wait_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
