# Generated by Django 3.1 on 2020-09-01 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queuer', '0007_auto_20200901_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='total_wait_time',
        ),
    ]
