# Generated by Django 3.1 on 2020-09-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuer', '0008_remove_queue_total_wait_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
