# Generated by Django 3.1 on 2020-09-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queuer', '0009_queue_paused'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='open',
            new_name='opened',
        ),
    ]
